// ignore_for_file: prefer_single_quotes

final validCartTotals = {
  "grand_total": 309.96,
  "base_grand_total": 309.96,
  "subtotal": 344.4,
  "base_subtotal": 344.4,
  "discount_amount": -34.44,
  "base_discount_amount": -34.44,
  "subtotal_with_discount": 309.96,
  "base_subtotal_with_discount": 309.96,
  "shipping_amount": 0,
  "base_shipping_amount": 0,
  "shipping_discount_amount": 0,
  "base_shipping_discount_amount": 0,
  "tax_amount": 0,
  "base_tax_amount": 0,
  "weee_tax_applied_amount": null,
  "shipping_tax_amount": 0,
  "base_shipping_tax_amount": 0,
  "subtotal_incl_tax": 344.4,
  "shipping_incl_tax": 0,
  "base_shipping_incl_tax": 0,
  "base_currency_code": "USD",
  "quote_currency_code": "USD",
  "coupon_code": "annual_discount_order",
  "items_qty": 10,
  "items": [
    {
      "item_id": 1143828,
      "price": 17.49,
      "base_price": 17.49,
      "qty": 3,
      "row_total": 52.47,
      "base_row_total": 52.47,
      "row_total_with_discount": 0,
      "tax_amount": 0,
      "base_tax_amount": 0,
      "tax_percent": 0,
      "discount_amount": 5.25,
      "base_discount_amount": 5.25,
      "discount_percent": 10,
      "price_incl_tax": 17.49,
      "base_price_incl_tax": 17.49,
      "row_total_incl_tax": 52.47,
      "base_row_total_incl_tax": 52.47,
      "options": "[]",
      "weee_tax_applied_amount": null,
      "weee_tax_applied": null,
      "name": "Scotts® Turf Builder® Lawn Food (North)"
    },
    {
      "item_id": 1143829,
      "price": 49.99,
      "base_price": 49.99,
      "qty": 3,
      "row_total": 149.97,
      "base_row_total": 149.97,
      "row_total_with_discount": 0,
      "tax_amount": 0,
      "base_tax_amount": 0,
      "tax_percent": 0,
      "discount_amount": 14.99,
      "base_discount_amount": 14.99,
      "discount_percent": 10,
      "price_incl_tax": 49.99,
      "base_price_incl_tax": 49.99,
      "row_total_incl_tax": 149.97,
      "base_row_total_incl_tax": 149.97,
      "options": "[]",
      "weee_tax_applied_amount": null,
      "weee_tax_applied": null,
      "name": "Scotts® Turf Builder® Thick'R Lawn® Bermudagrass"
    },
    {
      "item_id": 1143830,
      "price": 69.99,
      "base_price": 69.99,
      "qty": 1,
      "row_total": 69.99,
      "base_row_total": 69.99,
      "row_total_with_discount": 0,
      "tax_amount": 0,
      "base_tax_amount": 0,
      "tax_percent": 0,
      "discount_amount": 7,
      "base_discount_amount": 7,
      "discount_percent": 10,
      "price_incl_tax": 69.99,
      "base_price_incl_tax": 69.99,
      "row_total_incl_tax": 69.99,
      "base_row_total_incl_tax": 69.99,
      "options": "[]",
      "weee_tax_applied_amount": null,
      "weee_tax_applied": null,
      "name": "Scotts® Turf Builder® Summer Lawn Food"
    },
    {
      "item_id": 1143831,
      "price": 23.99,
      "base_price": 23.99,
      "qty": 3,
      "row_total": 71.97,
      "base_row_total": 71.97,
      "row_total_with_discount": 0,
      "tax_amount": 0,
      "base_tax_amount": 0,
      "tax_percent": 0,
      "discount_amount": 7.2,
      "base_discount_amount": 7.2,
      "discount_percent": 10,
      "price_incl_tax": 23.99,
      "base_price_incl_tax": 23.99,
      "row_total_incl_tax": 71.97,
      "base_row_total_incl_tax": 71.97,
      "options": "[]",
      "weee_tax_applied_amount": null,
      "weee_tax_applied": null,
      "name": "Scotts® Turf Builder® Weed & Feed (5M)"
    }
  ],
};

final seasonalCartTotals = {
  "grand_total": 17.49,
  "base_grand_total": 17.49,
  "subtotal": 17.49,
  "base_subtotal": 17.49,
  "discount_amount": 0,
  "base_discount_amount": 0,
  "subtotal_with_discount": 17.49,
  "base_subtotal_with_discount": 17.49,
  "shipping_amount": 0,
  "base_shipping_amount": 0,
  "shipping_discount_amount": 0,
  "base_shipping_discount_amount": 0,
  "tax_amount": 0,
  "base_tax_amount": 0,
  "weee_tax_applied_amount": null,
  "shipping_tax_amount": 0,
  "base_shipping_tax_amount": 0,
  "subtotal_incl_tax": 17.49,
  "shipping_incl_tax": 0,
  "base_shipping_incl_tax": 0,
  "base_currency_code": "USD",
  "quote_currency_code": "USD",
  "items_qty": 1,
  "items": [
    {
      "item_id": 1150567,
      "price": 17.49,
      "base_price": 17.49,
      "qty": 1,
      "row_total": 17.49,
      "base_row_total": 17.49,
      "row_total_with_discount": 0,
      "tax_amount": 0,
      "base_tax_amount": 0,
      "tax_percent": 0,
      "discount_amount": 0,
      "base_discount_amount": 0,
      "discount_percent": 0,
      "price_incl_tax": 17.49,
      "base_price_incl_tax": 17.49,
      "row_total_incl_tax": 17.49,
      "base_row_total_incl_tax": 17.49,
      "options": "[]",
      "weee_tax_applied_amount": null,
      "weee_tax_applied": null,
      "extension_attributes": {"sku": "22305"},
      "name": "Scotts® Turf Builder® Lawn Food (North)"
    }
  ],
};

final seasonalCartTotalsWithAddOns = {
  "grand_total": 34.98,
  "base_grand_total": 34.98,
  "subtotal": 34.98,
  "base_subtotal": 34.98,
  "discount_amount": 0,
  "base_discount_amount": 0,
  "subtotal_with_discount": 34.98,
  "base_subtotal_with_discount": 34.98,
  "shipping_amount": 0,
  "base_shipping_amount": 0,
  "shipping_discount_amount": 0,
  "base_shipping_discount_amount": 0,
  "tax_amount": 0,
  "base_tax_amount": 0,
  "weee_tax_applied_amount": null,
  "shipping_tax_amount": 0,
  "base_shipping_tax_amount": 0,
  "subtotal_incl_tax": 34.98,
  "shipping_incl_tax": 0,
  "base_shipping_incl_tax": 0,
  "base_currency_code": "USD",
  "quote_currency_code": "USD",
  "items_qty": 2,
  "items": [
    {
      "item_id": 1150567,
      "price": 17.49,
      "base_price": 17.49,
      "qty": 1,
      "row_total": 17.49,
      "base_row_total": 17.49,
      "row_total_with_discount": 0,
      "tax_amount": 0,
      "base_tax_amount": 0,
      "tax_percent": 0,
      "discount_amount": 0,
      "base_discount_amount": 0,
      "discount_percent": 0,
      "price_incl_tax": 17.49,
      "base_price_incl_tax": 17.49,
      "row_total_incl_tax": 17.49,
      "base_row_total_incl_tax": 17.49,
      "options": "[]",
      "weee_tax_applied_amount": null,
      "weee_tax_applied": null,
      "extension_attributes": {"sku": "22305"},
      "name": "Scotts® Turf Builder® Lawn Food (North)"
    },
    {
      "item_id": 1,
      "quote_id": "cb2qFQqMzILKJi9he8KY5LE2UGUc8lkp",
      "price": 17.49,
      "base_price": 17.49,
      "qty": 1,
      "row_total": 17.49,
      "base_row_total": 17.49,
      "row_total_with_discount": 0,
      "tax_amount": 0,
      "base_tax_amount": 0,
      "tax_percent": 0,
      "discount_amount": 0,
      "base_discount_amount": 0,
      "discount_percent": 0,
      "price_incl_tax": 17.49,
      "base_price_incl_tax": 17.49,
      "row_total_incl_tax": 17.49,
      "base_row_total_incl_tax": 17.49,
      "options": "[]",
      "weee_tax_applied_amount": null,
      "weee_tax_applied": null,
      "extension_attributes": {"sku": "76121"},
      "name": "Scotts® Turf Builder® with Edgeguard Mini Spreader"
    }
  ],
};

final annualCartTotals = {
  "grand_total": 62.96,
  "base_grand_total": 62.96,
  "subtotal": 69.96,
  "base_subtotal": 69.96,
  "discount_amount": -7,
  "base_discount_amount": -7,
  "subtotal_with_discount": 62.96,
  "base_subtotal_with_discount": 62.96,
  "shipping_amount": 0,
  "base_shipping_amount": 0,
  "shipping_discount_amount": 0,
  "base_shipping_discount_amount": 0,
  "tax_amount": 0,
  "base_tax_amount": 0,
  "weee_tax_applied_amount": null,
  "shipping_tax_amount": 0,
  "base_shipping_tax_amount": 0,
  "subtotal_incl_tax": 69.96,
  "shipping_incl_tax": 0,
  "base_shipping_incl_tax": 0,
  "base_currency_code": "USD",
  "quote_currency_code": "USD",
  "coupon_code": "annual_discount_order",
  "items_qty": 4,
  "items": [
    {
      "item_id": 1150831,
      "price": 17.49,
      "base_price": 17.49,
      "qty": 4,
      "row_total": 69.96,
      "base_row_total": 69.96,
      "row_total_with_discount": 0,
      "tax_amount": 0,
      "base_tax_amount": 0,
      "tax_percent": 0,
      "discount_amount": 7,
      "base_discount_amount": 7,
      "discount_percent": 10,
      "price_incl_tax": 17.49,
      "base_price_incl_tax": 17.49,
      "row_total_incl_tax": 69.96,
      "base_row_total_incl_tax": 69.96,
      "options": "[]",
      "weee_tax_applied_amount": null,
      "weee_tax_applied": null,
      "extension_attributes": {"sku": "22305"},
      "name": "Scotts® Turf Builder® Lawn Food (North)"
    }
  ],
};

final addOnProducts = {
  'addOnProducts': [
    {
      "name": "Scotts® Turf Builder® with Edgeguard Mini Spreader",
      "isAddOn": true,
      "childProducts": [
        {
          "description":
              "Broadcast spreader with exclusive EdgeGuard® technology. Holds up to 5,000 Sq. Ft. of Scotts® lawn products.  ",
          "quantity": 1,
          "coverage": 1000000,
          "shortDescription":
              "Broadcast spreader with exclusive EdgeGuard® technology. Holds up to 5,000 Sq. Ft. of Scotts® lawn products.  ",
          "price": 36.990000,
          "thumbnailImage":
              "https://images.scottsprogram.com/prod/pub/media/catalog/product/s/p/spreader.10.png",
          "sku": "76121",
          "thumbnailLabel": ""
        }
      ],
      "parentSku": "8541",
      "applicationWindow": {
        "zoneId": 5,
        "shipEndDate": "2020-12-17T00:00:00.000Z",
        "seasonSlug": "add-ons",
        "startingWeekNumber": 1,
        "startDate": "2020-01-01T00:00:00.000Z",
        "zoneName": "Zone 5",
        "season": "Add Ons",
        "shipStartDate": "2020-11-05T11:26:01.711Z",
        "isWholeYear": true,
        "endDate": "2020-12-31T00:00:00.000Z"
      }
    },
    {
      "name": "Scotts® Turf Builder® with Edgeguard Super-Mini Spreader",
      "isAddOn": true,
      "childProducts": [
        {
          "description":
              "Broadcast spreader with exclusive EdgeGuard® technology. Holds up to 5,000 Sq. Ft. of Scotts® lawn products.  ",
          "quantity": 1,
          "coverage": 1000000,
          "shortDescription":
              "Broadcast spreader with exclusive EdgeGuard® technology. Holds up to 5,000 Sq. Ft. of Scotts® lawn products.  ",
          "price": 36.990000,
          "thumbnailImage":
              "https://images.scottsprogram.com/prod/pub/media/catalog/product/s/p/spreader.10.png",
          "sku": "76122",
          "thumbnailLabel": ""
        }
      ],
      "parentSku": "8542",
      "applicationWindow": {
        "zoneId": 5,
        "shipEndDate": "2020-12-17T00:00:00.000Z",
        "seasonSlug": "add-ons",
        "startingWeekNumber": 1,
        "startDate": "2020-01-01T00:00:00.000Z",
        "zoneName": "Zone 5",
        "season": "Add Ons",
        "shipStartDate": "2020-11-05T11:26:01.711Z",
        "isWholeYear": true,
        "endDate": "2020-12-31T00:00:00.000Z"
      },
    },
  ]
};
