import 'package:my_lawn/config/colors_config.dart';

final products = [
  {
    'id': 1,
    'name': 'Scotts PatchMaster Something Something Something',
    'startDate': DateTime.utc(2019, 6, 10),
    'endDate': DateTime.utc(2019, 6, 31),
    'smallBags': 1,
    'largeBags': 0,
    'isArchived': true,
    'applied': true,
    'skipped': false,
    'addedByMe': false,
    'shipmentSkipped': false,
    'color': Styleguide.color_blue_2,
    'isSubscribed': false,
  },
  {
    'id': 2,
    'name': 'Scotts PatchMaster Something Something Something',
    'startDate': DateTime.utc(2019, 7, 10),
    'endDate': DateTime.utc(2019, 7, 31),
    'smallBags': 2,
    'largeBags': 1,
    'isArchived': false,
    'applied': true,
    'skipped': false,
    'addedByMe': false,
    'shipmentSkipped': false,
    'color': Styleguide.color_blue_2,
    'isSubscribed': false,
  },
  {
    'id': 7,
    'name': 'Scotts PatchMaster Something Something Something',
    'startDate': DateTime.utc(2020, 7, 10),
    'endDate': DateTime.utc(2020, 7, 20),
    'smallBags': 1,
    'largeBags': 1,
    'isArchived': false,
    'applied': false,
    'skipped': false,
    'addedByMe': false,
    'shipmentSkipped': false,
    'color': Styleguide.color_red_2,
    'isSubscribed': false,
  },
  {
    'id': 3,
    'name': 'Scotts PatchMaster Something Something Something',
    'startDate': DateTime.utc(2020, 7, 21),
    'endDate': DateTime.utc(2020, 8, 31),
    'smallBags': 1,
    'largeBags': 1,
    'isArchived': false,
    'applied': false,
    'skipped': true,
    'addedByMe': false,
    'shipmentSkipped': false,
    'color': Styleguide.color_red_2,
    'isSubscribed': false,
  },
  {
    'id': 4,
    'name': 'Scotts PatchMaster Something Something Something',
    'startDate': DateTime.utc(2020, 8, 10),
    'endDate': DateTime.utc(2020, 9, 31),
    'smallBags': 2,
    'largeBags': 2,
    'isArchived': false,
    'applied': false,
    'skipped': false,
    'addedByMe': true,
    'shipmentSkipped': false,
    'color': Styleguide.color_yellow_2,
    'isSubscribed': false,
  },
  {
    'id': 5,
    'name': 'Scotts PatchMaster Something Something Something',
    'startDate': DateTime.utc(2020, 9, 10),
    'endDate': DateTime.utc(2020, 8, 31),
    'smallBags': 2,
    'largeBags': 2,
    'isArchived': false,
    'applied': false,
    'skipped': false,
    'addedByMe': false,
    'shipmentSkipped': false,
    'color': Styleguide.color_orange_2,
    'isSubscribed': true,
  },
  {
    'id': 6,
    'name': 'Scotts PatchMaster Something Something Something',
    'startDate': DateTime.utc(2021, 10, 10),
    'endDate': DateTime.utc(2021, 10, 31),
    'smallBags': 0,
    'largeBags': 0,
    'isArchived': false,
    'applied': false,
    'skipped': false,
    'addedByMe': false,
    'shipmentSkipped': true,
    'color': Styleguide.color_blue_2,
    'isSubscribed': true,
  },
];
